if Mix.env() == :dev do
  defmodule Mix.Tasks.Forge.GenDiagram do
    @shortdoc "Generates docs/architecture.md with an AshDiagram ERD of the Projects domain"

    @moduledoc """
    Generates `docs/architecture.md` containing a Mermaid entity-relationship
    diagram for the `Forge.Projects` Ash domain.

    ## Usage

        mix forge.gen_diagram

    The file is written to `docs/architecture.md` and is safe to commit.
    """

    use Mix.Task

    @output_path "docs/architecture.md"

    @impl Mix.Task
    def run(_args) do
      Mix.Task.run("app.start")

      diagram = AshDiagram.Data.EntityRelationship.for_domains([Forge.Projects])
      mermaid = AshDiagram.compose(diagram)

      content = """
      # Forge — Architecture Diagram

      > Auto-generated by `mix forge.gen_diagram` via [AshDiagram](https://hex.pm/packages/ash_diagram).
      > Do not edit manually.

      ## Entity Relationship Diagram

      ```mermaid
      #{mermaid}
      ```
      """

      File.write!(@output_path, content)
      Mix.shell().info("#{IO.ANSI.green()}* updated#{IO.ANSI.reset()} #{@output_path}")
    end
  end
end
