defmodule Forge.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :tasks_enabled, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:projects) do
      remove :tasks_enabled
    end
  end
end
