defmodule Forge.Repo.Migrations.AddCurrencyToProjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :currency, :text, null: false, default: "SEK"
    end
  end

  def down do
    alter table(:projects) do
      remove :currency
    end
  end
end
