defmodule Forge.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Use SQL with IF NOT EXISTS to avoid duplicate column errors when running migrations multiple times
    execute("ALTER TABLE projects ADD COLUMN IF NOT EXISTS sort_order bigint DEFAULT 0 NOT NULL")

    execute(
      "ALTER TABLE projects ADD COLUMN IF NOT EXISTS tasks_enabled boolean DEFAULT false NOT NULL"
    )
  end

  def down do
    # Only remove columns if they exist
    execute("ALTER TABLE projects DROP COLUMN IF EXISTS tasks_enabled")
    execute("ALTER TABLE projects DROP COLUMN IF EXISTS sort_order")
  end
end
