defmodule Forge.Repo.Migrations.AddTasks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text, null: false
      add :status, :text, null: false, default: "todo"
      add :priority, :text, null: false, default: "medium"
      add :due_date, :date
      add :sort_order, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "tasks_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :journal_entry_id,
          references(:journal_entries,
            column: :id,
            name: "tasks_journal_entry_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:tasks, "tasks_project_id_fkey")

    drop constraint(:tasks, "tasks_journal_entry_id_fkey")

    drop table(:tasks)
  end
end
