defmodule Forge.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add_if_not_exists :sort_order, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:projects) do
      remove :sort_order
    end
  end
end
