defmodule Forge.Repo.Migrations.CreateInitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "idea"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :category_id, :uuid, null: false
    end

    create table(:journal_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "journal_entries_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:projects) do
      modify :category_id,
             references(:categories,
               column: :id,
               name: "projects_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:categories) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :icon, :text
      add :color, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:categories, [:slug], name: "categories_unique_slug_index")

    create table(:bom_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :quantity, :bigint, null: false, default: 1
      add :unit, :text
      add :supplier, :text
      add :link, :text
      add :unit_price, :decimal
      add :currency, :text, default: "SEK"
      add :status, :text, null: false, default: "needed"
      add :notes, :text
      add :sort_order, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "bom_items_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:bom_items, "bom_items_project_id_fkey")

    drop table(:bom_items)

    drop_if_exists unique_index(:categories, [:slug], name: "categories_unique_slug_index")

    alter table(:categories) do
      remove :updated_at
      remove :inserted_at
      remove :color
      remove :icon
      remove :slug
      remove :name
    end

    drop constraint(:projects, "projects_category_id_fkey")

    alter table(:projects) do
      modify :category_id, :uuid
    end

    drop table(:categories)

    drop constraint(:journal_entries, "journal_entries_project_id_fkey")

    drop table(:journal_entries)

    drop table(:projects)
  end
end
