defmodule Forge.Repo.Migrations.AddTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:task_tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :task_id,
          references(:tasks,
            column: :id,
            name: "task_tags_task_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false

      add :tag_id, :uuid, null: false, primary_key: true
    end

    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:task_tags) do
      modify :tag_id,
             references(:tags,
               column: :id,
               name: "task_tags_tag_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:task_tags, [:task_id, :tag_id], name: "task_tags_unique_task_tag_index")

    alter table(:tags) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "tags_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:tags, [:name, :project_id], name: "tags_unique_name_per_project_index")
  end

  def down do
    drop_if_exists unique_index(:tags, [:name, :project_id],
                     name: "tags_unique_name_per_project_index"
                   )

    drop constraint(:tags, "tags_project_id_fkey")

    alter table(:tags) do
      remove :project_id
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop_if_exists unique_index(:task_tags, [:task_id, :tag_id],
                     name: "task_tags_unique_task_tag_index"
                   )

    drop constraint(:task_tags, "task_tags_tag_id_fkey")

    alter table(:task_tags) do
      modify :tag_id, :uuid
    end

    drop table(:tags)

    drop constraint(:task_tags, "task_tags_task_id_fkey")

    drop table(:task_tags)
  end
end
