defmodule Forge.Repo.Migrations.AddAttachments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :cover_image_id, :uuid
    end

    create table(:attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :type, :text, null: false
      add :title, :text, null: false
      add :description, :text
      add :filename, :text, null: false
      add :content_type, :text, null: false
      add :storage_path, :text, null: false
      add :size_bytes, :bigint, null: false
      add :sort_order, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "attachments_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:attachments, "attachments_project_id_fkey")

    drop table(:attachments)

    alter table(:projects) do
      remove :cover_image_id
    end
  end
end
