defmodule Forge.AshDiagramTest do
  use ExUnit.Case, async: true
  use ExUnitProperties

  @moduletag :schema
  @moduledoc """
  Validates that Ash resource definitions are correctly configured for AshDiagram
  to generate an accurate architecture diagram.

  These tests check the SOURCE (resource definitions), not the generated file.
  The diagram itself is regenerated by `mix forge.gen_diagram` and should never
  be manually edited.
  """

  @resources [
    Forge.Projects.Project,
    Forge.Projects.ProjectGroup,
    Forge.Projects.Task,
    Forge.Projects.BomItem,
    Forge.Projects.JournalEntry
  ]

  @expected_public_attributes %{
    Forge.Projects.Project =>
      ~w(name description tech_stack url notes budget status color project_group_id)a,
    Forge.Projects.ProjectGroup => ~w(name)a,
    Forge.Projects.Task =>
      ~w(title description status priority pin_status due_date sort_order project_id parent_task_id)a,
    Forge.Projects.BomItem =>
      ~w(name quantity unit supplier link unit_price currency status notes sort_order project_id)a,
    Forge.Projects.JournalEntry => ~w(title body sort_order project_id)a
  }

  @expected_public_relationships %{
    Forge.Projects.Project => ~w(project_group tasks bom_items journal_entries)a,
    Forge.Projects.ProjectGroup => ~w(projects)a,
    Forge.Projects.Task => ~w(project parent_task subtasks)a,
    Forge.Projects.BomItem => ~w(project)a,
    Forge.Projects.JournalEntry => ~w(project)a
  }

  describe "public attributes (required for AshDiagram to render fields)" do
    property "every resource has all expected attributes marked public?" do
      check all(resource <- member_of(@resources)) do
        expected = @expected_public_attributes[resource]
        public_names = Ash.Resource.Info.public_attributes(resource) |> Enum.map(& &1.name)
        missing = expected -- public_names

        assert missing == [],
               "#{inspect(resource)}: attributes not public (AshDiagram will omit them): #{inspect(missing)}"
      end
    end
  end

  describe "public relationships (required for AshDiagram to render edges)" do
    property "every resource has all expected relationships marked public?" do
      check all(resource <- member_of(@resources)) do
        expected = @expected_public_relationships[resource]
        public_names = Ash.Resource.Info.public_relationships(resource) |> Enum.map(& &1.name)
        missing = expected -- public_names

        assert missing == [],
               "#{inspect(resource)}: relationships not public (AshDiagram will omit them): #{inspect(missing)}"
      end
    end
  end

  describe "FK on_delete constraints" do
    property "Task.parent_task uses on_delete: :delete (matches DB CASCADE)" do
      check all(_ <- constant(:ok)) do
        refs = AshPostgres.DataLayer.Info.references(Forge.Projects.Task)
        ref = Enum.find(refs, &(&1.relationship == :parent_task))

        assert ref != nil, "No postgres reference declared for Task.parent_task"

        assert ref.on_delete == :delete,
               "Task.parent_task on_delete should be :delete, got #{inspect(ref.on_delete)}"
      end
    end

    property "Project.project_group uses on_delete: :nilify (matches DB SET NULL)" do
      check all(_ <- constant(:ok)) do
        refs = AshPostgres.DataLayer.Info.references(Forge.Projects.Project)
        ref = Enum.find(refs, &(&1.relationship == :project_group))

        assert ref != nil, "No postgres reference declared for Project.project_group"

        assert ref.on_delete == :nilify,
               "Project.project_group on_delete should be :nilify, got #{inspect(ref.on_delete)}"
      end
    end
  end

  describe "all resources are registered in the Projects domain" do
    property "every expected resource is registered in Forge.Projects domain" do
      check all(resource <- member_of(@resources)) do
        registered = Ash.Domain.Info.resources(Forge.Projects)

        assert resource in registered,
               "#{inspect(resource)} is not registered in Forge.Projects domain"
      end
    end
  end
end
